DROP TABLE "FAV_RECRUIT";

CREATE TABLE "FAV_RECRUIT" (
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"RECRUIT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "FAV_RECRUIT"."MEM_NO" IS '회원_시퀀스_번호 (PFK)';

COMMENT ON COLUMN "FAV_RECRUIT"."RECRUIT_NO" IS '공고_시퀀스_번호(PFK)';

DROP TABLE "CV_EDUCATION";

CREATE TABLE "CV_EDUCATION" (
	"CV_NO"	NUMBER		NOT NULL,
	"EDU_NAME"	NVARCHAR2(20)		NOT NULL,
	"EDU_START_DATE"	DATE		NOT NULL,
	"EDU_END_DATE"	DATE		NOT NULL,
	"EDU_MAJOR"	NVARCHAR2(20)		NOT NULL,
	"EDU_CODE_NO"	NUMBER		NOT NULL,
	"EDU_STATUS_CODE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_EDUCATION"."CV_NO" IS '이력서_시퀀스_번호(PFK)';

COMMENT ON COLUMN "CV_EDUCATION"."EDU_NAME" IS '학력_학교명';

COMMENT ON COLUMN "CV_EDUCATION"."EDU_START_DATE" IS '학력_입학년월일';

COMMENT ON COLUMN "CV_EDUCATION"."EDU_END_DATE" IS '학력_졸업년월일';

COMMENT ON COLUMN "CV_EDUCATION"."EDU_MAJOR" IS '학력_전공';

COMMENT ON COLUMN "CV_EDUCATION"."EDU_CODE_NO" IS '학력학위_코드';

COMMENT ON COLUMN "CV_EDUCATION"."EDU_STATUS_CODE_NO" IS '학력상태_코드';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(50)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_EDIT_DATE"	DATE		NULL,
	"BOARD_READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_STATUS_CODE"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_STATUS_DATE"	DATE		NULL,
	"BOARD_THUMBNAIL_URL"	VARCHAR2(500)		NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글_시퀀스_번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글_제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글_내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글_작성일';

COMMENT ON COLUMN "BOARD"."BOARD_EDIT_DATE" IS '게시글_수정일';

COMMENT ON COLUMN "BOARD"."BOARD_READ_COUNT" IS '게시글_조회수';

COMMENT ON COLUMN "BOARD"."BOARD_STATUS_CODE" IS '게시글_상태구분_코드';

COMMENT ON COLUMN "BOARD"."BOARD_STATUS_DATE" IS '게시글_정지/삭제_날짜';

COMMENT ON COLUMN "BOARD"."BOARD_THUMBNAIL_URL" IS '게시글_썸네일_URL';

COMMENT ON COLUMN "BOARD"."MEM_NO" IS '회원_시퀀스_번호 (FK)';

DROP TABLE "ADMIN";

CREATE TABLE "ADMIN" (
	"ADMIN_NO"	NUMBER		NOT NULL,
	"ADMIN_ID"	NVARCHAR2(15)		NOT NULL,
	"ADMIN_PW"	NVARCHAR2(100)		NOT NULL,
	"ADMIN_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"ADMIN_NAME"	NVARCHAR2(20)		NOT NULL,
	"ADMIN_TEL"	NVARCHAR2(11)		NOT NULL,
	"ADMIN_EMAIL"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ADMIN"."ADMIN_NO" IS '관리자_시퀀스_번호(PK)';

COMMENT ON COLUMN "ADMIN"."ADMIN_ID" IS '관리자_아이디(UNIQUE)';

COMMENT ON COLUMN "ADMIN"."ADMIN_PW" IS '관리자_비밀번호';

COMMENT ON COLUMN "ADMIN"."ADMIN_NICKNAME" IS '관리자_닉네임(UNIQUE)';

COMMENT ON COLUMN "ADMIN"."ADMIN_NAME" IS '관리자_이름';

COMMENT ON COLUMN "ADMIN"."ADMIN_TEL" IS '관리자_전화번호(UNIQUE)';

COMMENT ON COLUMN "ADMIN"."ADMIN_EMAIL" IS '관리자_이메일(UNIQUE)';

DROP TABLE "REPORT_CATEGORY";

CREATE TABLE "REPORT_CATEGORY" (
	"REPORT_CATEGORY_CODE"	NUMBER		NOT NULL,
	"REPORT_CATEGORY_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REPORT_CATEGORY"."REPORT_CATEGORY_CODE" IS '신고_카테고리_코드(PK)';

COMMENT ON COLUMN "REPORT_CATEGORY"."REPORT_CATEGORY_NAME" IS '신고_카테리고_이름';

DROP TABLE "BOARD_IMG";

CREATE TABLE "BOARD_IMG" (
	"BOARD_IMG_NO"	NUMBER		NOT NULL,
	"BOARD_IMG_URL"	NVARCHAR2(500)		NOT NULL,
	"BOARD_IMG_NAME"	NVARCHAR2(255)		NOT NULL,
	"BOARD_IMG_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_NO" IS '게시글_이미지_번호(PK)';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_URL" IS '게시글_이미지_URL';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_NAME" IS '게시글_이미지_이름';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_UPLOAD_DATE" IS '게시글_이미지_업로드_날짜';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글_시퀀스_번호(FK)';

DROP TABLE "REFUND";

CREATE TABLE "REFUND" (
	"REFUND_ID"	NVARCHAR2(200)		NOT NULL,
	"REFUND_REQUEST_AT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REFUND_SUCCESS_AT"	DATE		NULL,
	"REFUND_STATUS"	NVARCHAR2(20)		NULL,
	"REFUND_AMOUNT"	NUMBER		NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"ORDER_ID"	NVARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "REFUND"."REFUND_AMOUNT" IS '환불액';

COMMENT ON COLUMN "REFUND"."MEM_NO" IS '회원_시퀀스_번호 (PK)';

COMMENT ON COLUMN "REFUND"."ORDER_ID" IS '주문_ID';

DROP TABLE "FAV_CORP";

CREATE TABLE "FAV_CORP" (
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"CORP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "FAV_CORP"."MEM_NO" IS '회원_시퀀스_번호 (PK)';

COMMENT ON COLUMN "FAV_CORP"."CORP_NO" IS '기업_시퀀스_번호(PK)';

DROP TABLE "CORP_INFO";

CREATE TABLE "CORP_INFO" (
	"CORP_NO"	NUMBER		NOT NULL,
	"CORP_REG_NO"	NVARCHAR2(10)		NOT NULL,
	"CORP_TYPE"	NVARCHAR2(10)		NULL,
	"CORP_NAME"	NVARCHAR2(50)		NOT NULL,
	"CORP_LOGO"	NVARCHAR2(100)		NULL,
	"CORP_CEO_NAME"	NVARCHAR2(20)		NOT NULL,
	"CORP_ADDR"	NVARCHAR2(100)		NOT NULL,
	"CORP_OPEN_DATE"	DATE		NOT NULL,
	"CORP_HOME_LINK"	NVARCHAR2(100)		NOT NULL,
	"CORP_BM"	NVARCHAR2(100)		NOT NULL,
	"CORP_DETAIL"	NVARCHAR2(100)		NULL,
	"CORP_BENEFIT"	NVARCHAR2(1000)		NULL,
	"CORP_BENEFIT_DETAIL"	NVARCHAR2(2000)		NULL,
	"CORP_BAN_FL"	CHAR(1)		NULL,
	"CORP_BAN_DATE"	DATE		NULL
);

COMMENT ON COLUMN "CORP_INFO"."CORP_NO" IS '기업_시퀀스_번호(PK)';

COMMENT ON COLUMN "CORP_INFO"."CORP_REG_NO" IS '기업_사업자등록번호';

COMMENT ON COLUMN "CORP_INFO"."CORP_TYPE" IS '기업_형태';

COMMENT ON COLUMN "CORP_INFO"."CORP_NAME" IS '기업_회사명';

COMMENT ON COLUMN "CORP_INFO"."CORP_LOGO" IS '기업_로고';

COMMENT ON COLUMN "CORP_INFO"."CORP_CEO_NAME" IS '기업_대표명';

COMMENT ON COLUMN "CORP_INFO"."CORP_ADDR" IS '기업_회사주소';

COMMENT ON COLUMN "CORP_INFO"."CORP_OPEN_DATE" IS '기업_개업일자';

COMMENT ON COLUMN "CORP_INFO"."CORP_HOME_LINK" IS '기업_홈페이지링크';

COMMENT ON COLUMN "CORP_INFO"."CORP_BM" IS '기업_주요사업';

COMMENT ON COLUMN "CORP_INFO"."CORP_DETAIL" IS '기업_기업소개상세';

COMMENT ON COLUMN "CORP_INFO"."CORP_BENEFIT" IS '기업_복리후생_카테고리';

COMMENT ON COLUMN "CORP_INFO"."CORP_BENEFIT_DETAIL" IS '기업_복리후생_내용';

COMMENT ON COLUMN "CORP_INFO"."CORP_BAN_FL" IS '기업_정지_플래그';

COMMENT ON COLUMN "CORP_INFO"."CORP_BAN_DATE" IS '기업_정지일';

DROP TABLE "SUBSCRIPTION";

CREATE TABLE "SUBSCRIPTION" (
	"SUB_NO"	NUMBER		NOT NULL,
	"MEM_GRADE"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"SUB_START_AT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"SUB_END_AT"	DATE		NULL,
	"SUB_UPDATE_AT"	DATE		NULL,
	"SUB_PAY_AT"	DATE		NULL,
	"SUB_STATUS"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "SUBSCRIPTION"."SUB_NO" IS '구독_번호';

COMMENT ON COLUMN "SUBSCRIPTION"."MEM_GRADE" IS '회원_멤버쉽구분_번호(FK)';

COMMENT ON COLUMN "SUBSCRIPTION"."MEM_NO" IS '회원_시퀀스_번호 (FK)';

COMMENT ON COLUMN "SUBSCRIPTION"."SUB_START_AT" IS '구독_시작일';

COMMENT ON COLUMN "SUBSCRIPTION"."SUB_END_AT" IS '구독_만기일';

COMMENT ON COLUMN "SUBSCRIPTION"."SUB_UPDATE_AT" IS '구독_변경일';

COMMENT ON COLUMN "SUBSCRIPTION"."SUB_PAY_AT" IS '구독_결제일';

COMMENT ON COLUMN "SUBSCRIPTION"."SUB_STATUS" IS '구독_상태구분_코드';

DROP TABLE "RECRUIT_CV";

CREATE TABLE "RECRUIT_CV" (
	"RECRUIT_CV_NO"	NUMBER		NOT NULL,
	"RECRUIT_CV_EDU"	NUMBER		NULL,
	"RECRUIT_CV_CAREER"	NUMBER		NULL,
	"RECRUIT_CV_PDF_TITLE"	NVARCHAR2(200)		NULL,
	"RECRUIT_CV_PDF_PATH"	NVARCHAR2(200)		NULL,
	"RECRUIT_CV_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"RECRUIT_CV_CHECK_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"RECRUIT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_CV_NO" IS '지원_이력서_시퀀스_번호(PK)';

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_CV_EDU" IS '지원자_학력';

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_CV_CAREER" IS '지원자_경력';

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_CV_PDF_TITLE" IS '지원자_이력서_PDF_제목';

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_CV_PDF_PATH" IS '지원자_이력서_PDF_경로';

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_CV_DATE" IS '지원자_지원날짜';

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_CV_CHECK_FL" IS '지원자_이력서_다운로드_여부';

COMMENT ON COLUMN "RECRUIT_CV"."MEM_NO" IS '회원_시퀀스_번호 (PK)';

COMMENT ON COLUMN "RECRUIT_CV"."RECRUIT_NO" IS '공고_시퀀스_번호(PK)';

DROP TABLE "CORP_MEM";

CREATE TABLE "CORP_MEM" (
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"CORP_MEM_ROLE_CHECK"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CORP_MEM_DEPT"	NVARCHAR(50)		NULL,
	"CORP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CORP_MEM"."MEM_NO" IS '회원_시퀀스_번호 (PFK)';

COMMENT ON COLUMN "CORP_MEM"."CORP_MEM_ROLE_CHECK" IS '기업회원_담당구분';

COMMENT ON COLUMN "CORP_MEM"."CORP_MEM_DEPT" IS '기업회원_부서명';

COMMENT ON COLUMN "CORP_MEM"."CORP_NO" IS '기업_시퀀스_번호(FK)';

DROP TABLE "CV";

CREATE TABLE "CV" (
	"CV_NO"	NUMBER		NOT NULL,
	"CV_RESUME"	NVARCHAR2(2000)		NULL,
	"CV_ALIAS"	NVARCHAR2(30)		NULL,
	"CV_IMG_PATH"	NVARCHAR2(200)		NULL,
	"CV_MAIN_FL"	CHAR(1)		NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL
);
COMMENT ON COLUMN "CV"."CV_NO" IS '이력서_시퀀스_번호(PK)';

COMMENT ON COLUMN "CV"."CV_RESUME" IS '이력서_자기소개서';

COMMENT ON COLUMN "CV"."CV_ALIAS" IS '이력서_별칭';

COMMENT ON COLUMN "CV"."CV_IMG_PATH" IS '이력서_이미지경로';

COMMENT ON COLUMN "CV"."CV_MAIN_FL" IS '이력서_대표_플래그';

COMMENT ON COLUMN "CV"."MEM_NO" IS '회원_시퀀스_번호 (PK)';

DROP TABLE "REPORT";

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_TARGET_NO"	NUMBER		NOT NULL,
	"REPORT_TARGET_TYPE"	NVARCHAR2(10)		NOT NULL,
	"REPORT_CONTENT"	NVARCHAR2(100)		NULL,
	"REPORT_STATUS"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_CATEGORY_CODE"	NUMBER		NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL
);


COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고_시퀀스_번호(PK)';

COMMENT ON COLUMN "REPORT"."REPORT_TARGET_NO" IS '신고_대상_시퀀스_번호';

COMMENT ON COLUMN "REPORT"."REPORT_TARGET_TYPE" IS '신고_대상_종류';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고_내용';

COMMENT ON COLUMN "REPORT"."REPORT_STATUS" IS '신고_처리상태';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고_날짜';

COMMENT ON COLUMN "REPORT"."REPORT_CATEGORY_CODE" IS '신고_카테고리_코드(FK)';

COMMENT ON COLUMN "REPORT"."MEM_NO" IS '회원_시퀀스_번호 (PK)';

DROP TABLE "SUPPORT_NOTICE";

CREATE TABLE "SUPPORT_NOTICE" (
	"SUPPORT_NOTICE_CODE"	NUMBER		NOT NULL,
	"SUPPORT_NOTICE_TITLE"	NVARCHAR(50)		NOT NULL,
	"SUPPORT_NOTICE_CONTENT"	VARCHAR(4000)		NOT NULL,
	"SUPPORT_CATEGORY_CODE"	NUMBER		NOT NULL,
	"ADMIN_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SUPPORT_NOTICE"."SUPPORT_NOTICE_CODE" IS '문의_공지_코드(PK)';

COMMENT ON COLUMN "SUPPORT_NOTICE"."SUPPORT_NOTICE_TITLE" IS '문의_공지_제목';

COMMENT ON COLUMN "SUPPORT_NOTICE"."SUPPORT_NOTICE_CONTENT" IS '문의_공지_내용';

COMMENT ON COLUMN "SUPPORT_NOTICE"."SUPPORT_CATEGORY_CODE" IS '문의_카테고리_코드(PK)';

COMMENT ON COLUMN "SUPPORT_NOTICE"."ADMIN_NO" IS '관리자_시퀀스_번호(PK)';

DROP TABLE "SUPPORT_CATEGORY";

CREATE TABLE "SUPPORT_CATEGORY" (
	"SUPPORT_CATEGORY_CODE"	NUMBER		NOT NULL,
	"SUPPORT_CATEGORY_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "SUPPORT_CATEGORY"."SUPPORT_CATEGORY_CODE" IS '문의_카테고리_코드(PK)';

COMMENT ON COLUMN "SUPPORT_CATEGORY"."SUPPORT_CATEGORY_NAME" IS '문의_카테리고_이름';

DROP TABLE "SUPPORT";

CREATE TABLE "SUPPORT" (
	"SUPPORT_NO"	NUMBER		NOT NULL,
	"SUPPORT_TITLE"		VARCHAR2(50)		NOT NULL,
	"SUPPORT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"SUPPORT_ANSWER"	VARCHAR2(4000)		NULL,
	"SUPPORT_STATUS"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"ADMIN_NO"	NUMBER		NOT NULL,
	"SUPPORT_CATEGORY_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SUPPORT"."SUPPORT_NO" IS '문의_시퀀스_번호(PK)';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_TITLE" IS '문의_제목';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_CONTENT" IS '문의_내용';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_ANSWER" IS '문의_답변';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_STATUS" IS '문의_처리상태';

COMMENT ON COLUMN "SUPPORT"."MEM_NO" IS '회원_시퀀스_번호 (FK)';

COMMENT ON COLUMN "SUPPORT"."ADMIN_NO" IS '관리자_시퀀스_번호(FK)';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_CATEGORY_CODE" IS '문의_카테고리_코드(PK)';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"MEM_ID"	NVARCHAR2(15)		NOT NULL,
	"MEM_PW"	NVARCHAR2(100)		NOT NULL,
	"MEM_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEM_NAME"	NVARCHAR2(20)		NOT NULL,
	"MEM_TEL"	NVARCHAR2(13)		NOT NULL,
	"MEM_EMAIL"	NVARCHAR2(20)		NOT NULL,
	"MEM_BIRTHDAY"	DATE		NOT NULL,
	"MEM_GENDER"	CHAR(1)		NOT NULL,
	"MEM_ADDR"	NVARCHAR2(100)		NULL,
	"MEM_ENROLLDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEM_SMS_FL"	CHAR(1)		NOT NULL,
	"MEM_TYPE"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_STATUS"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_STATUS_DATE"	DATE		NULL,
	"MEM_PROFILE_PATH"	NVARCHAR2(200)		NULL,
	"MEM_GRADE"	NUMBER	DEFAULT 0	NOT NULL,
	"MEMBERSHIP_UPDATE"	DATE		NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_NO" IS '회원_시퀀스_번호 (PK)';

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '회원_아이디(UNIQUE)';

COMMENT ON COLUMN "MEMBER"."MEM_PW" IS '회원_비밀번호';

COMMENT ON COLUMN "MEMBER"."MEM_NICKNAME" IS '회원_닉네임';

COMMENT ON COLUMN "MEMBER"."MEM_NAME" IS '회원_이름';

COMMENT ON COLUMN "MEMBER"."MEM_TEL" IS '회원_전화번호(UNIQUE)';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL" IS '회원_이메일(UNIQUE)';

COMMENT ON COLUMN "MEMBER"."MEM_BIRTHDAY" IS '회원_생년월일';

COMMENT ON COLUMN "MEMBER"."MEM_GENDER" IS '회원_성별';

COMMENT ON COLUMN "MEMBER"."MEM_ADDR" IS '회원_주소';

COMMENT ON COLUMN "MEMBER"."MEM_ENROLLDATE" IS '회원_가입날짜';

COMMENT ON COLUMN "MEMBER"."MEM_SMS_FL" IS '마케팅_동의_플래그';

COMMENT ON COLUMN "MEMBER"."MEM_TYPE" IS '회원_구분';

COMMENT ON COLUMN "MEMBER"."MEM_STATUS" IS '회원_상태구분_코드';

COMMENT ON COLUMN "MEMBER"."MEM_STATUS_DATE" IS '회원_정지/탈퇴_날짜';

COMMENT ON COLUMN "MEMBER"."MEM_PROFILE_PATH" IS '회원_프로필_이미지경로';

COMMENT ON COLUMN "MEMBER"."MEM_GRADE" IS '개인회원_멤버쉽구분_번호(FK)';

COMMENT ON COLUMN "MEMBER"."MEMBERSHIP_UPDATE" IS '회원_멤버쉽_업데이트일';

DROP TABLE "RECRUIT";

CREATE TABLE "RECRUIT" (
	"RECRUIT_NO"	NUMBER		NOT NULL,
	"RECRUIT_TITLE"	NVARCHAR2(50)		NOT NULL,
	"RECRUIT_START_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RECRUIT_END_DATE"	DATE		NOT NULL,
	"RECRUIT_TYPE"	NVARCHAR2(15)		NOT NULL,
	"RECRUIT_DOCX"	NVARCHAR2(100)		NULL,
	"RECRUIT_APPLY"	NVARCHAR2(500)		NULL,
	"RECRUIT_RESULT_DATE"	DATE		NOT NULL,
	"RECRUIT_CORP_URL"	NVARCHAR2(50)		NULL,
	"RECRUIT_HIRE_DETAIL"	NVARCHAR2(1000)		NULL,
	"RECRUIT_JOB_NAME"	NVARCHAR2(50)		NOT NULL,
	"RECRUIT_JOB_DETAIL"	NVARCHAR2(500)		NOT NULL,
	"RECRUIT_JOB_AREA"	NVARCHAR2(100)		NOT NULL,
	"RECRUIT_CAREER"	NVARCHAR2(10)		NOT NULL,
	"RECRUIT_EDU"	NVARCHAR2(50)		NOT NULL,
	"RECRUIT_HEADCOUNT"	NUMBER		NOT NULL,
	"RECRUIT_SALARY"	NVARCHAR2(100)		NOT NULL,
	"RECRUIT_ETC"	NVARCHAR2(1000)		NULL,
	"RECRUIT_READCOUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"RECRUIT_STATUS"	NUMBER	DEFAULT 0	NOT NULL,
	"RECRUIT_STATUS_DATE"	DATE		NULL,
	"RECRUIT_WRITE_DATE"	DATE		NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "RECRUIT"."RECRUIT_NO" IS '공고_시퀀스_번호(PK)';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_TITLE" IS '공고_제목';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_START_DATE" IS '공고_채용시작일';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_END_DATE" IS '공고_채용종료일';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_TYPE" IS '공고_고용형태';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_DOCX" IS '공고_제출서류';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_APPLY" IS '공고_접수방법';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_RESULT_DATE" IS '공고_합격자발표일';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_CORP_URL" IS '공고_채용사이트URL';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_HIRE_DETAIL" IS '공고_채용단계상세설명';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_JOB_NAME" IS '공고_직무명';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_JOB_DETAIL" IS '공고_직무설명';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_JOB_AREA" IS '공고_근무지';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_CAREER" IS '공고_지원자격_경력';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_EDU" IS '공고_지원자격_학력';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_HEADCOUNT" IS '공고_모집인원';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_SALARY" IS '공고_연봉';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_ETC" IS '공고_기타사항';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_READCOUNT" IS '공고_조회수';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_STATUS" IS '공고_상태구분_코드';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_STATUS_DATE" IS '공고__정지/삭제_날짜';

COMMENT ON COLUMN "RECRUIT"."RECRUIT_WRITE_DATE" IS '공고_작성일';

COMMENT ON COLUMN "RECRUIT"."MEM_NO" IS '회원_시퀀스_번호 (PFK)';

DROP TABLE "BAN";

CREATE TABLE "BAN" (
	"BAN_NO"	NUMBER		NOT NULL,
	"BAN_CONTENT"	NVARCHAR2(100)		NOT NULL,
	"BAN_TARGET_NO"	NUMBER		NOT NULL,
	"BAN_TARGET_TYPE"	NVARCHAR2(10)		NOT NULL,
	"ADMIN_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BAN"."BAN_NO" IS '정지사유_시퀀스_번호';

COMMENT ON COLUMN "BAN"."BAN_CONTENT" IS '정지사유_내용';

COMMENT ON COLUMN "BAN"."BAN_TARGET_NO" IS '정지_대상_시퀀스_번호';

COMMENT ON COLUMN "BAN"."BAN_TARGET_TYPE" IS '정지_대상_종류';

COMMENT ON COLUMN "BAN"."ADMIN_NO" IS '관리자_시퀀스_번호(FK)';

DROP TABLE "CV_PORTFOLIO";

CREATE TABLE "CV_PORTFOLIO" (
	"PORT_ID"	NVARCHAR2(30)		NOT NULL,
	"PORT_NAME"	NVARCHAR2(20)		NOT NULL,
	"PORT_START_DATE"	DATE		NOT NULL,
	"PORT_END_DATE"	DATE		NOT NULL,
	"PORT_CONTENT"	NVARCHAR2(1000)		NULL,
	"CV_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_PORTFOLIO"."PORT_ID" IS '포폴_번호(PK)';

COMMENT ON COLUMN "CV_PORTFOLIO"."PORT_NAME" IS '포폴_이름';

COMMENT ON COLUMN "CV_PORTFOLIO"."PORT_START_DATE" IS '포폴_시작일';

COMMENT ON COLUMN "CV_PORTFOLIO"."PORT_END_DATE" IS '포폴_종료일';

COMMENT ON COLUMN "CV_PORTFOLIO"."PORT_CONTENT" IS '포폴_내용';

COMMENT ON COLUMN "CV_PORTFOLIO"."CV_NO" IS '이력서_시퀀스_번호(PK)';

DROP TABLE "CV_LANGUAGE";

CREATE TABLE "CV_LANGUAGE" (
	"LANG_ID"	NVARCHAR2(30)		NOT NULL,
	"LANG_NAME"	NVARCHAR2(20)		NOT NULL,
	"LANG_DATE"	DATE		NOT NULL,
	"LANG_TYPE"	NVARCHAR2(20)		NOT NULL,
	"LANG_SCORE"	NUMBER		NULL,
	"CV_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_LANGUAGE"."LANG_ID" IS '어학_번호PK)';

COMMENT ON COLUMN "CV_LANGUAGE"."LANG_NAME" IS '어학_이름';

COMMENT ON COLUMN "CV_LANGUAGE"."LANG_DATE" IS '어학_취득일';

COMMENT ON COLUMN "CV_LANGUAGE"."LANG_TYPE" IS '어학_언어';

COMMENT ON COLUMN "CV_LANGUAGE"."LANG_SCORE" IS '어학_점수';

COMMENT ON COLUMN "CV_LANGUAGE"."CV_NO" IS '이력서_시퀀스_번호(PK)';

DROP TABLE "CV_EDU_CODE";

CREATE TABLE "CV_EDU_CODE" (
	"EDU_CODE_NO"	NUMBER		NOT NULL,
	"EDU_CODE_DETAIL"	NVARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "CV_EDU_CODE"."EDU_CODE_NO" IS '학력학위_코드(PK)';

COMMENT ON COLUMN "CV_EDU_CODE"."EDU_CODE_DETAIL" IS '학력학위_구분';

DROP TABLE "CV_EDU_STATUS";

CREATE TABLE "CV_EDU_STATUS" (
	"EDU_STATUS_CODE_NO"	NUMBER		NOT NULL,
	"EDU_STATUS_DETAIL"	NVARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "CV_EDU_STATUS"."EDU_STATUS_CODE_NO" IS '학력상태_코드(PK)';

COMMENT ON COLUMN "CV_EDU_STATUS"."EDU_STATUS_DETAIL" IS '학력상태_구분';

DROP TABLE "CV_EXPERIENCE";

CREATE TABLE "CV_EXPERIENCE" (
	"EXP_ID"	NVARCHAR2(30)		NOT NULL,
	"EXP_NAME"	NVARCHAR2(20)		NOT NULL,
	"EXP_START_DATE"	DATE		NOT NULL,
	"EXP_END_DATE"	DATE		NOT NULL,
	"EXP_DEPT"	NVARCHAR2(20)		NOT NULL,
	"EXP_CONTENT"	NVARCHAR2(1000)		NULL,
	"CV_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_EXPERIENCE"."EXP_ID" IS '경력_번호(PK)';

COMMENT ON COLUMN "CV_EXPERIENCE"."EXP_NAME" IS '경력_이름';

COMMENT ON COLUMN "CV_EXPERIENCE"."EXP_START_DATE" IS '경력_시작일';

COMMENT ON COLUMN "CV_EXPERIENCE"."EXP_END_DATE" IS '경력_종료일';

COMMENT ON COLUMN "CV_EXPERIENCE"."EXP_DEPT" IS '경력_부서';

COMMENT ON COLUMN "CV_EXPERIENCE"."EXP_CONTENT" IS '경력_내용';

COMMENT ON COLUMN "CV_EXPERIENCE"."CV_NO" IS '이력서_시퀀스_번호(PK)';

DROP TABLE "CV_TRAINING";

CREATE TABLE "CV_TRAINING" (
	"TRAIN_ID"	NVARCHAR2(30)		NOT NULL,
	"TRAIN_NAME"	NVARCHAR2(20)		NOT NULL,
	"TRAIN_START_DATE"	DATE		NOT NULL,
	"TRAIN_END_DATE"	DATE		NOT NULL,
	"TRAIN_ORGANIZATION"	NVARCHAR2(20)		NOT NULL,
	"TRAIN_CONTENT"	NVARCHAR2(1000)		NULL,
	"CV_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_TRAINING"."TRAIN_ID" IS '교육_번호(PK)';

COMMENT ON COLUMN "CV_TRAINING"."TRAIN_NAME" IS '교육_이름';

COMMENT ON COLUMN "CV_TRAINING"."TRAIN_START_DATE" IS '교육_시작일';

COMMENT ON COLUMN "CV_TRAINING"."TRAIN_END_DATE" IS '교육_종료일';

COMMENT ON COLUMN "CV_TRAINING"."TRAIN_ORGANIZATION" IS '교육_기관';

COMMENT ON COLUMN "CV_TRAINING"."TRAIN_CONTENT" IS '교육_내용';

COMMENT ON COLUMN "CV_TRAINING"."CV_NO" IS '이력서_시퀀스_번호(PK)';

DROP TABLE "FAV_BOARD";

CREATE TABLE "FAV_BOARD" (
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "FAV_BOARD"."MEM_NO" IS '회원_시퀀스_번호 (PFK)';

COMMENT ON COLUMN "FAV_BOARD"."BOARD_NO" IS '게시글_시퀀스_번호(PFK)';

DROP TABLE "PAYMENT";

CREATE TABLE "PAYMENT" (
	"ORDER_ID"	NVARCHAR2(200)		NOT NULL,
	"ORDER_NAME"	NVARCHAR2(200)		NOT NULL,
	"PAYMENT_KEY"	NVARCHAR2(200)		NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"CURRENCY"	NVARCHAR2(5)		NOT NULL,
	"TOTAL_AMOUNT"	NUMBER		NOT NULL,
	"COUNTRY"	NVARCHAR2(2)		NOT NULL,
	"PAY_TYPE"	NVARCHAR2(20)		NOT NULL,
	"STATUS"	NVARCHAR2(20)		NOT NULL,
	"REQUESTED_AT"	DATE		NOT NULL,
	"APPROVED_AT"	DATE		NOT NULL,
	"UPDATED_AT"	DATE		NULL,
	"CANCELS"	NVARCHAR2(5)		NULL,
	"FAILURE"	NVARCHAR2(5)		NULL,
	"BALANCE_AMOUNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."ORDER_ID" IS '주문_ID';

COMMENT ON COLUMN "PAYMENT"."ORDER_NAME" IS '주문_명';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_KEY" IS '결제_내역_구분_용도';

COMMENT ON COLUMN "PAYMENT"."MEM_NO" IS '회원_시퀀스_번호 (FK)';

COMMENT ON COLUMN "PAYMENT"."CURRENCY" IS '통화';

COMMENT ON COLUMN "PAYMENT"."TOTAL_AMOUNT" IS '결제_금액';

COMMENT ON COLUMN "PAYMENT"."COUNTRY" IS '국가';

COMMENT ON COLUMN "PAYMENT"."PAY_TYPE" IS '결제_유형';

COMMENT ON COLUMN "PAYMENT"."STATUS" IS '결제_상태';

COMMENT ON COLUMN "PAYMENT"."REQUESTED_AT" IS '결제_요청_시각';

COMMENT ON COLUMN "PAYMENT"."APPROVED_AT" IS '결제_승인_시각';

COMMENT ON COLUMN "PAYMENT"."UPDATED_AT" IS '주문_수정_시각';

COMMENT ON COLUMN "PAYMENT"."CANCELS" IS '취소_정보';

COMMENT ON COLUMN "PAYMENT"."FAILURE" IS '실패_정보';

COMMENT ON COLUMN "PAYMENT"."BALANCE_AMOUNT" IS '남은_결제_금액';

DROP TABLE "CV_AWARD";

CREATE TABLE "CV_AWARD" (
	"AWARD_ID"	NVARCHAR2(30)		NOT NULL,
	"AWARD_NAME"	NVARCHAR2(20)		NOT NULL,
	"AWARD_DATE"	DATE		NOT NULL,
	"AWARD_ORG"	NVARCHAR2(20)		NOT NULL,
	"CV_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_AWARD"."AWARD_ID" IS '수상_번호(PK)';

COMMENT ON COLUMN "CV_AWARD"."AWARD_NAME" IS '수상_이름';

COMMENT ON COLUMN "CV_AWARD"."AWARD_DATE" IS '수상_취득일';

COMMENT ON COLUMN "CV_AWARD"."AWARD_ORG" IS '수상_기관';

COMMENT ON COLUMN "CV_AWARD"."CV_NO" IS '이력서_시퀀스_번호(PK)';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	NVARCHAR2(1000)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE		NOT NULL,
	"COMMENT_EDIT_DATE"	DATE		NULL,
	"COMMENT_STATUS"	NUMBER	DEFAULT 0	NOT NULL,
	"COMMENT_STATUS_DATE"	DATE		NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO"	NUMBER		NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글_시퀀스_번호(PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글_내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글_작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_EDIT_DATE" IS '댓글_수정일';

COMMENT ON COLUMN "COMMENT"."COMMENT_STATUS" IS '댓글_상태구분_코드';

COMMENT ON COLUMN "COMMENT"."COMMENT_STATUS_DATE" IS '댓글_정지/삭제_날짜';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글_시퀀스_번호(FK)';

COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모_댓글_시퀀스_번호(FK)';

COMMENT ON COLUMN "COMMENT"."MEM_NO" IS '회원_시퀀스_번호 (PK)';

DROP TABLE "AUTH";

CREATE TABLE "AUTH" (
	"AUTH_NO"	NUMBER		NOT NULL,
	"AUTH_PHONE"	NVARCHAR2(11)		NOT NULL,
	"AUTH_KEY"	NVARCHAR2(10)		NOT NULL,
	"AUTH_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH"."AUTH_NO" IS '인증_구분_번호(PK)';

COMMENT ON COLUMN "AUTH"."AUTH_PHONE" IS '인증_전화번호';

COMMENT ON COLUMN "AUTH"."AUTH_KEY" IS '인증_인증번호';

COMMENT ON COLUMN "AUTH"."AUTH_TIME" IS '인증_생성시간';

DROP TABLE "BILLING_KEY";

CREATE TABLE "BILLING_KEY" (
	"BILLING_KEY"	NVARCHAR2(200)		NOT NULL,
	"BILLING_METHOD"	NVARCHAR2(20)		NOT NULL,
	"CARD_COMPANY"	NVARCHAR2(50)		NOT NULL,
	"CARD_NUMBER"	NVARCHAR2(25)		NOT NULL,
	"CARD_TYPE"	NVARCHAR2(10)		NOT NULL,
	"OWNER_TYPE"	NVARCHAR2(10)		NOT NULL,
	"ISSUER_CODE"	NVARCHAR2(10)		NOT NULL,
	"ACQUIRER_CODE"	NVARCHAR2(10)		NOT NULL,
	"AUTHENTICATED_AT"	DATE		NOT NULL,
	"MEM_NO"	NVARCHAR2(50)		NOT NULL,
	"MID"	NVARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "BILLING_KEY"."BILLING_KEY" IS '빌링_키';

COMMENT ON COLUMN "BILLING_KEY"."BILLING_METHOD" IS '결제_수단';

COMMENT ON COLUMN "BILLING_KEY"."CARD_COMPANY" IS '카드사';

COMMENT ON COLUMN "BILLING_KEY"."CARD_NUMBER" IS '카드번호';

COMMENT ON COLUMN "BILLING_KEY"."CARD_TYPE" IS '카드_유형(신용/체크)';

COMMENT ON COLUMN "BILLING_KEY"."OWNER_TYPE" IS '카드_소지자_유형';

COMMENT ON COLUMN "BILLING_KEY"."ISSUER_CODE" IS '카드_발급사_코드';

COMMENT ON COLUMN "BILLING_KEY"."ACQUIRER_CODE" IS '카드_매입사_코드';

COMMENT ON COLUMN "BILLING_KEY"."AUTHENTICATED_AT" IS '빌링_키_인증_시각';

COMMENT ON COLUMN "BILLING_KEY"."MEM_NO" IS '회원_시퀀스_번호 (FK)';

COMMENT ON COLUMN "BILLING_KEY"."MID" IS '가맹점_식별코드';

DROP TABLE "CV_MILITARY";

CREATE TABLE "CV_MILITARY" (
	"CV_NO"	NUMBER		NOT NULL,
	"CV_MILI_CLASS"	NVARCHAR2(10)		NULL,
	"CV_MILI_BRANCH"	NVARCHAR2(20)		NULL,
	"CV_MILI_START_DATE"	DATE		NULL,
	"CV_MILI_END_DATE"	DATE		NULL
);

COMMENT ON COLUMN "CV_MILITARY"."CV_NO" IS '이력서_시퀀스_번호(PFK)';

COMMENT ON COLUMN "CV_MILITARY"."CV_MILI_CLASS" IS '병역_구분';

COMMENT ON COLUMN "CV_MILITARY"."CV_MILI_BRANCH" IS '병역_군별';

COMMENT ON COLUMN "CV_MILITARY"."CV_MILI_START_DATE" IS '병역_복무시작';

COMMENT ON COLUMN "CV_MILITARY"."CV_MILI_END_DATE" IS '병역_복무종료';

DROP TABLE "CV_QUALIFY";

CREATE TABLE "CV_QUALIFY" (
	"QUALIFY_ID"	NVARCHAR2(30)		NOT NULL,
	"QUALIFY_NAME"	NVARCHAR2(20)		NOT NULL,
	"QUALIFY_DATE"	DATE		NOT NULL,
	"QUALIFY_ORG"	NVARCHAR2(20)		NOT NULL,
	"CV_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_QUALIFY"."QUALIFY_ID" IS '자격증_번호(PK)';

COMMENT ON COLUMN "CV_QUALIFY"."QUALIFY_NAME" IS '자격증_이름';

COMMENT ON COLUMN "CV_QUALIFY"."QUALIFY_DATE" IS '자격증_취득일';

COMMENT ON COLUMN "CV_QUALIFY"."QUALIFY_ORG" IS '자격증_기관';

COMMENT ON COLUMN "CV_QUALIFY"."CV_NO" IS '이력서_시퀀스_번호(PK)';

DROP TABLE "MEMBER_GRADE";

CREATE TABLE "MEMBER_GRADE" (
	"MEM_GRADE"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_GRADE_NAME"	NVARCHAR2(10)		NOT NULL,
	"MEM_GRADE_PRICE"	NUMBER(10,2)	DEFAULT 0	NOT NULL,
	"MEMBERSHIP_BENEFIT"	NVARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_GRADE"."MEM_GRADE" IS '회원_멤버쉽구분_번호(PK)';

COMMENT ON COLUMN "MEMBER_GRADE"."MEM_GRADE_NAME" IS '회원_멤버쉽구분_이름';

COMMENT ON COLUMN "MEMBER_GRADE"."MEM_GRADE_PRICE" IS '회원_멤버쉽_가격';

COMMENT ON COLUMN "MEMBER_GRADE"."MEMBERSHIP_BENEFIT" IS '회원_멤버십_설명';

DROP TABLE "CV_OUTER";

CREATE TABLE "CV_OUTER" (
	"OUTER_ID"	NVARCHAR2(30)		NOT NULL,
	"OUTER_NAME"	NVARCHAR2(20)		NOT NULL,
	"OUTER_START_DATE"	DATE		NOT NULL,
	"OUTER_END_DATE"	DATE		NOT NULL,
	"OUTER_ORGANIZATION"	NVARCHAR2(20)		NOT NULL,
	"OUTER_CONTENT"	NVARCHAR2(1000)		NULL,
	"CV_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CV_OUTER"."OUTER_ID" IS '대외활동_번호(PK)';

COMMENT ON COLUMN "CV_OUTER"."OUTER_NAME" IS '대외활동_이름';

COMMENT ON COLUMN "CV_OUTER"."OUTER_START_DATE" IS '대외활동_시작일';

COMMENT ON COLUMN "CV_OUTER"."OUTER_END_DATE" IS '대외활동_종료일';

COMMENT ON COLUMN "CV_OUTER"."OUTER_ORGANIZATION" IS '대외활동_기관';

COMMENT ON COLUMN "CV_OUTER"."OUTER_CONTENT" IS '대외활동_내용';

COMMENT ON COLUMN "CV_OUTER"."CV_NO" IS '이력서_시퀀스_번호(PK)';

ALTER TABLE "FAV_RECRUIT" ADD CONSTRAINT "PK_FAV_RECRUIT" PRIMARY KEY (
	"MEM_NO",
	"RECRUIT_NO"
);

ALTER TABLE "CV_EDUCATION" ADD CONSTRAINT "PK_CV_EDUCATION" PRIMARY KEY (
	"CV_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_NO"
);

ALTER TABLE "REPORT_CATEGORY" ADD CONSTRAINT "PK_REPORT_CATEGORY" PRIMARY KEY (
	"REPORT_CATEGORY_CODE"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"BOARD_IMG_NO"
);

ALTER TABLE "REFUND" ADD CONSTRAINT "PK_REFUND" PRIMARY KEY (
	"REFUND_ID"
);

ALTER TABLE "FAV_CORP" ADD CONSTRAINT "PK_FAV_CORP" PRIMARY KEY (
	"MEM_NO",
	"CORP_NO"
);

ALTER TABLE "CORP_INFO" ADD CONSTRAINT "PK_CORP_INFO" PRIMARY KEY (
	"CORP_NO"
);

ALTER TABLE "SUBSCRIPTION" ADD CONSTRAINT "PK_SUBSCRIPTION" PRIMARY KEY (
	"SUB_NO"
);

ALTER TABLE "RECRUIT_CV" ADD CONSTRAINT "PK_RECRUIT_CV" PRIMARY KEY (
	"RECRUIT_CV_NO"
);

ALTER TABLE "CORP_MEM" ADD CONSTRAINT "PK_CORP_MEM" PRIMARY KEY (
	"MEM_NO"
);

ALTER TABLE "CV" ADD CONSTRAINT "PK_CV" PRIMARY KEY (
	"CV_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "SUPPORT_NOTICE" ADD CONSTRAINT "PK_SUPPORT_NOTICE" PRIMARY KEY (
	"SUPPORT_NOTICE_CODE"
);

ALTER TABLE "SUPPORT_CATEGORY" ADD CONSTRAINT "PK_SUPPORT_CATEGORY" PRIMARY KEY (
	"SUPPORT_CATEGORY_CODE"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "PK_SUPPORT" PRIMARY KEY (
	"SUPPORT_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_NO"
);

ALTER TABLE "RECRUIT" ADD CONSTRAINT "PK_RECRUIT" PRIMARY KEY (
	"RECRUIT_NO"
);

ALTER TABLE "BAN" ADD CONSTRAINT "PK_BAN" PRIMARY KEY (
	"BAN_NO"
);

ALTER TABLE "CV_PORTFOLIO" ADD CONSTRAINT "PK_CV_PORTFOLIO" PRIMARY KEY (
	"PORT_ID"
);

ALTER TABLE "CV_LANGUAGE" ADD CONSTRAINT "PK_CV_LANGUAGE" PRIMARY KEY (
	"LANG_ID"
);

ALTER TABLE "CV_EDU_CODE" ADD CONSTRAINT "PK_CV_EDU_CODE" PRIMARY KEY (
	"EDU_CODE_NO"
);

ALTER TABLE "CV_EDU_STATUS" ADD CONSTRAINT "PK_CV_EDU_STATUS" PRIMARY KEY (
	"EDU_STATUS_CODE_NO"
);

ALTER TABLE "CV_EXPERIENCE" ADD CONSTRAINT "PK_CV_EXPERIENCE" PRIMARY KEY (
	"EXP_ID"
);

ALTER TABLE "CV_TRAINING" ADD CONSTRAINT "PK_CV_TRAINING" PRIMARY KEY (
	"TRAIN_ID"
);

ALTER TABLE "FAV_BOARD" ADD CONSTRAINT "PK_FAV_BOARD" PRIMARY KEY (
	"MEM_NO",
	"BOARD_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"ORDER_ID"
);

ALTER TABLE "CV_AWARD" ADD CONSTRAINT "PK_CV_AWARD" PRIMARY KEY (
	"AWARD_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "AUTH" ADD CONSTRAINT "PK_AUTH" PRIMARY KEY (
	"AUTH_NO"
);

ALTER TABLE "BILLING_KEY" ADD CONSTRAINT "PK_BILLING_KEY" PRIMARY KEY (
	"BILLING_KEY"
);

ALTER TABLE "CV_MILITARY" ADD CONSTRAINT "PK_CV_MILITARY" PRIMARY KEY (
	"CV_NO"
);

ALTER TABLE "CV_QUALIFY" ADD CONSTRAINT "PK_CV_QUALIFY" PRIMARY KEY (
	"QUALIFY_ID"
);

ALTER TABLE "MEMBER_GRADE" ADD CONSTRAINT "PK_MEMBER_GRADE" PRIMARY KEY (
	"MEM_GRADE"
);

ALTER TABLE "CV_OUTER" ADD CONSTRAINT "PK_CV_OUTER" PRIMARY KEY (
	"OUTER_ID"
);

ALTER TABLE "FAV_RECRUIT" ADD CONSTRAINT "FK_MEMBER_TO_FAV_RECRUIT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "FAV_RECRUIT" ADD CONSTRAINT "FK_RECRUIT_TO_FAV_RECRUIT_1" FOREIGN KEY (
	"RECRUIT_NO"
)
REFERENCES "RECRUIT" (
	"RECRUIT_NO"
);

ALTER TABLE "CV_EDUCATION" ADD CONSTRAINT "FK_CV_TO_CV_EDUCATION_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "CV_EDUCATION" ADD CONSTRAINT "FK_CV_EDU_CODE_TO_CV_EDUCATION_1" FOREIGN KEY (
	"EDU_CODE_NO"
)
REFERENCES "CV_EDU_CODE" (
	"EDU_CODE_NO"
);

ALTER TABLE "CV_EDUCATION" ADD CONSTRAINT "FK_CV_EDU_STATUS_TO_CV_EDUCATION_1" FOREIGN KEY (
	"EDU_STATUS_CODE_NO"
)
REFERENCES "CV_EDU_STATUS" (
	"EDU_STATUS_CODE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REFUND" ADD CONSTRAINT "FK_MEMBER_TO_REFUND_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "REFUND" ADD CONSTRAINT "FK_PAYMENT_TO_REFUND_1" FOREIGN KEY (
	"ORDER_ID"
)
REFERENCES "PAYMENT" (
	"ORDER_ID"
);

ALTER TABLE "FAV_CORP" ADD CONSTRAINT "FK_MEMBER_TO_FAV_CORP_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "FAV_CORP" ADD CONSTRAINT "FK_CORP_INFO_TO_FAV_CORP_1" FOREIGN KEY (
	"CORP_NO"
)
REFERENCES "CORP_INFO" (
	"CORP_NO"
);

ALTER TABLE "SUBSCRIPTION" ADD CONSTRAINT "FK_MEMBER_GRADE_TO_SUBSCRIPTION_1" FOREIGN KEY (
	"MEM_GRADE"
)
REFERENCES "MEMBER_GRADE" (
	"MEM_GRADE"
);

ALTER TABLE "SUBSCRIPTION" ADD CONSTRAINT "FK_MEMBER_TO_SUBSCRIPTION_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "RECRUIT_CV" ADD CONSTRAINT "FK_MEMBER_TO_RECRUIT_CV_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "RECRUIT_CV" ADD CONSTRAINT "FK_RECRUIT_TO_RECRUIT_CV_1" FOREIGN KEY (
	"RECRUIT_NO"
)
REFERENCES "RECRUIT" (
	"RECRUIT_NO"
);

ALTER TABLE "CORP_MEM" ADD CONSTRAINT "FK_MEMBER_TO_CORP_MEM_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "CORP_MEM" ADD CONSTRAINT "FK_CORP_INFO_TO_CORP_MEM_1" FOREIGN KEY (
	"CORP_NO"
)
REFERENCES "CORP_INFO" (
	"CORP_NO"
);

ALTER TABLE "CV" ADD CONSTRAINT "FK_MEMBER_TO_CV_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_REPORT_CATEGORY_TO_REPORT_1" FOREIGN KEY (
	"REPORT_CATEGORY_CODE"
)
REFERENCES "REPORT_CATEGORY" (
	"REPORT_CATEGORY_CODE"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "SUPPORT_NOTICE" ADD CONSTRAINT "FK_SUPPORT_CATEGORY_TO_SUPPORT_NOTICE_1" FOREIGN KEY (
	"SUPPORT_CATEGORY_CODE"
)
REFERENCES "SUPPORT_CATEGORY" (
	"SUPPORT_CATEGORY_CODE"
);

ALTER TABLE "SUPPORT_NOTICE" ADD CONSTRAINT "FK_ADMIN_TO_SUPPORT_NOTICE_1" FOREIGN KEY (
	"ADMIN_NO"
)
REFERENCES "ADMIN" (
	"ADMIN_NO"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "FK_MEMBER_TO_SUPPORT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "FK_ADMIN_TO_SUPPORT_1" FOREIGN KEY (
	"ADMIN_NO"
)
REFERENCES "ADMIN" (
	"ADMIN_NO"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "FK_SUPPORT_CATEGORY_TO_SUPPORT_1" FOREIGN KEY (
	"SUPPORT_CATEGORY_CODE"
)
REFERENCES "SUPPORT_CATEGORY" (
	"SUPPORT_CATEGORY_CODE"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_MEMBER_GRADE_TO_MEMBER_1" FOREIGN KEY (
	"MEM_GRADE"
)
REFERENCES "MEMBER_GRADE" (
	"MEM_GRADE"
);

ALTER TABLE "RECRUIT" ADD CONSTRAINT "FK_CORP_MEM_TO_RECRUIT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "CORP_MEM" (
	"MEM_NO"
);

ALTER TABLE "BAN" ADD CONSTRAINT "FK_ADMIN_TO_BAN_1" FOREIGN KEY (
	"ADMIN_NO"
)
REFERENCES "ADMIN" (
	"ADMIN_NO"
);

ALTER TABLE "CV_PORTFOLIO" ADD CONSTRAINT "FK_CV_TO_CV_PORTFOLIO_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "CV_LANGUAGE" ADD CONSTRAINT "FK_CV_TO_CV_LANGUAGE_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "CV_EXPERIENCE" ADD CONSTRAINT "FK_CV_TO_CV_EXPERIENCE_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "CV_TRAINING" ADD CONSTRAINT "FK_CV_TO_CV_TRAINING_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "FAV_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_FAV_BOARD_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "FAV_BOARD" ADD CONSTRAINT "FK_BOARD_TO_FAV_BOARD_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
) ON DELETE CASCADE;

--ALTER TABLE FAV_BOARD DROP CONSTRAINT FK_BOARD_TO_FAV_BOARD_1; (FK조건 때매 게시글 삭제 안됨)

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_MEMBER_TO_PAYMENT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "CV_AWARD" ADD CONSTRAINT "FK_CV_TO_CV_AWARD_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"PARENT_COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "BILLING_KEY" ADD CONSTRAINT "FK_MEMBER_TO_BILLING_KEY_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "CV_MILITARY" ADD CONSTRAINT "FK_CV_TO_CV_MILITARY_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "CV_QUALIFY" ADD CONSTRAINT "FK_CV_TO_CV_QUALIFY_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

ALTER TABLE "CV_OUTER" ADD CONSTRAINT "FK_CV_TO_CV_OUTER_1" FOREIGN KEY (
	"CV_NO"
)
REFERENCES "CV" (
	"CV_NO"
);

COMMIT;

---------------------------------------------------

SELECT * FROM ALL_SEQUENCES;

CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CV_NO START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE SEQUENCE SEQ_CORP_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_RECRUIT_CV_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SUBSCRIPTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_REPORT_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SUBSCRIPTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_REPORT_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

SELECT * FROM BOARD;
