DROP TABLE IF EXISTS `CV_EDUCATION`;
DROP TABLE IF EXISTS `BOARD`;
DROP TABLE IF EXISTS `ADMIN`;
DROP TABLE IF EXISTS `REPORT_CATEGORY`;
DROP TABLE IF EXISTS `BOARD_IMG`;
DROP TABLE IF EXISTS `REFUND`;
DROP TABLE IF EXISTS `FAV_CORP`;
DROP TABLE IF EXISTS `CORP_INFO`;
DROP TABLE IF EXISTS `SUBSCRIPTION`;
DROP TABLE IF EXISTS `RECRUIT_CV`;
DROP TABLE IF EXISTS `CORP_MEM`;
DROP TABLE IF EXISTS `CV`;
DROP TABLE IF EXISTS `REPORT`;
DROP TABLE IF EXISTS `SUPPORT_NOTICE`;
DROP TABLE IF EXISTS `SUPPORT_CATEGORY`;
DROP TABLE IF EXISTS `SUPPORT`;
DROP TABLE IF EXISTS `MEMBER`;
DROP TABLE IF EXISTS `RECRUIT`;
DROP TABLE IF EXISTS `BAN`;
DROP TABLE IF EXISTS `CV_PORTFOLIO`;
DROP TABLE IF EXISTS `CV_LANGUAGE`;
DROP TABLE IF EXISTS `CV_EDU_CODE`;
DROP TABLE IF EXISTS `CV_EDU_STATUS`;
DROP TABLE IF EXISTS `CV_EXPERIENCE`;
DROP TABLE IF EXISTS `CV_TRAINING`;
DROP TABLE IF EXISTS `FAV_BOARD`;
DROP TABLE IF EXISTS `PAYMENT`;
DROP TABLE IF EXISTS `CV_AWARD`;
DROP TABLE IF EXISTS `COMMENT`;
DROP TABLE IF EXISTS `AUTH`;
DROP TABLE IF EXISTS `BILLING_KEY`;
DROP TABLE IF EXISTS `CV_MILITARY`;
DROP TABLE IF EXISTS `CV_QUALIFY`;
DROP TABLE IF EXISTS `MEMBER_GRADE`;
DROP TABLE IF EXISTS `CV_OUTER`;
DROP TABLE IF EXISTS `FAV_RECRUIT`;

-- 코드 테이블 (참조되는 테이블)
CREATE TABLE `REPORT_CATEGORY` (
    `REPORT_CATEGORY_CODE` NUMBER PRIMARY KEY,
    `REPORT_CATEGORY_NAME` NVARCHAR2(20) NOT NULL COMMENT '신고_카테리고_이름'
);

CREATE TABLE `SUPPORT_CATEGORY` (
    `SUPPORT_CATEGORY_CODE` NUMBER PRIMARY KEY,
    `SUPPORT_CATEGORY_NAME` NVARCHAR2(20) NOT NULL COMMENT '문의_카테리고_이름'
);

CREATE TABLE `CV_EDU_CODE` (
    `EDU_CODE_NO` NUMBER PRIMARY KEY,
    `EDU_CODE_DETAIL` NVARCHAR2(10) NOT NULL COMMENT '학력학위_구분'
);

CREATE TABLE `CV_EDU_STATUS` (
    `EDU_STATUS_CODE_NO` NUMBER PRIMARY KEY,
    `EDU_STATUS_DETAIL` NVARCHAR2(10) NOT NULL COMMENT '학력상태_구분'
);

CREATE TABLE `MEMBER_GRADE` (
    `MEM_GRADE_NO` NUMBER DEFAULT 0 PRIMARY KEY,
    `MEM_GRADE_NAME` NVARCHAR2(10) NOT NULL COMMENT '회원_멤버쉽구분_이름',
    `MEM_GRADE_PRICE` NUMBER(10,2) NOT NULL DEFAULT 0 COMMENT '회원_멤버쉽_가격'
);

-- 기본 테이블
CREATE TABLE `ADMIN` (
    `ADMIN_NO` NUMBER PRIMARY KEY,
    `ADMIN_ID` NVARCHAR2(15) NOT NULL COMMENT '관리자_아이디(UNIQUE)',
    `ADMIN_PW` NVARCHAR2(100) NOT NULL COMMENT '관리자_비밀번호',
    `ADMIN_NICKNAME` NVARCHAR2(10) NOT NULL COMMENT '관리자_닉네임(UNIQUE)',
    `ADMIN_NAME` NVARCHAR2(20) NOT NULL COMMENT '관리자_이름',
    `ADMIN_TEL` NVARCHAR2(11) NOT NULL COMMENT '관리자_전화번호(UNIQUE)',
    `ADMIN_EMAIL` NVARCHAR2(20) NOT NULL COMMENT '관리자_이메일(UNIQUE)'
);

CREATE TABLE `MEMBER` (
    `MEM_NO` NUMBER PRIMARY KEY,
    `MEM_ID` NVARCHAR2(15) NOT NULL COMMENT '회원_아이디(UNIQUE)',
    `MEM_PW` NVARCHAR2(100) NOT NULL COMMENT '회원_비밀번호',
    `MEM_NICKNAME` NVARCHAR2(10) NOT NULL COMMENT '회원_닉네임',
    `MEM_NAME` NVARCHAR2(20) NOT NULL COMMENT '회원_이름',
    `MEM_TEL` NVARCHAR2(11) NOT NULL COMMENT '회원_전화번호(UNIQUE)',
    `MEM_EMAIL` NVARCHAR2(20) NOT NULL COMMENT '회원_이메일(UNIQUE)',
    `MEM_BIRTHDAY` DATE NOT NULL COMMENT '회원_생년월일',
    `MEM_GENDER` CHAR(1) NOT NULL COMMENT '회원_성별',
    `MEM_ADDR` NVARCHAR2(100) NULL COMMENT '회원_주소',
    `MEM_ENROLLDATE` DATE NOT NULL DEFAULT SYSDATE COMMENT '회원_가입날짜',
    `MEM_SMS_FL` CHAR(1) NOT NULL COMMENT '마케팅_동의_플래그',
    `MEM_TYPE` NUMBER NOT NULL DEFAULT 0 COMMENT '회원_구분',
    `MEM_STATUS` NUMBER NOT NULL DEFAULT 0 COMMENT '회원_상태구분_코드',
    `MEM_STATUS_DATE` DATE NULL COMMENT '회원_정지/탈퇴_날짜',
    `MEM_PROFILE_PATH` NVARCHAR2(200) NULL COMMENT '회원_프로필_이미지경로',
    `MEM_GRADE` NUMBER NOT NULL DEFAULT 0 COMMENT '개인회원_멤버쉽구분_번호(FK)',
    `MEMBERSHIP_UPDATE` DATE NULL COMMENT '회원_멤버쉽_업데이트일',
    `CUSTOMER_KEY` NVARCHAR2(100) NULL COMMENT '회원_키',
    FOREIGN KEY (`MEM_GRADE`) REFERENCES `MEMBER_GRADE` (`MEM_GRADE_NO`)
);

CREATE TABLE `CORP_INFO` (
    `CORP_NO` NUMBER PRIMARY KEY,
    `CORP_REG_NO` NUMBER NOT NULL COMMENT '기업_사업자등록번호',
    `CORP_TYPE` NVARCHAR2(10) NULL COMMENT '기업_형태',
    `CORP_NAME` NVARCHAR2(50) NOT NULL COMMENT '기업_회사명',
    `CORP_LOGO` NVARCHAR2(100) NULL COMMENT '기업_로고',
    `CORP_CEO_NAME` NVARCHAR2(20) NOT NULL COMMENT '기업_대표명',
    `CORP_ADDR` NVARCHAR2(100) NOT NULL COMMENT '기업_회사주소',
    `CORP_OPEN_DATE` DATE NOT NULL COMMENT '기업_개업일자',
    `CORP_HOME_LINK` NVARCHAR2(100) NOT NULL COMMENT '기업_홈페이지링크',
    `CORP_BM` NVARCHAR2(100) NOT NULL COMMENT '기업_주요사업',
    `CORP_DETAIL` NVARCHAR2(100) NULL COMMENT '기업_기업소개상세',
    `CORP_BENEFIT` NVARCHAR2(1000) NULL COMMENT '기업_복리후생_카테고리',
    `CORP_BENEFIT_DETAIL` NVARCHAR2(2000) NULL COMMENT '기업_복리후생_내용',
    `CORP_BAN_FL` CHAR(1) NULL COMMENT '기업_정지_플래그',
    `CORP_BAN_DATE` DATE NULL COMMENT '기업_정지일'
);

CREATE TABLE `CORP_MEM` (
    `MEM_NO` NUMBER PRIMARY KEY,
    `CORP_MEM_ROLE_CHECK` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '기업회원_담당구분',
    `CORP_MEM_DEPT` NVARCHAR(50) NULL COMMENT '기업회원_부서명',
    `CORP_NO` NUMBER NOT NULL COMMENT '기업_시퀀스_번호(FK)',
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`),
    FOREIGN KEY (`CORP_NO`) REFERENCES `CORP_INFO` (`CORP_NO`)
);

CREATE TABLE `CV` (
    `CV_NO` NUMBER PRIMARY KEY,
    `CV_RESUME` NVARCHAR2(2000) NULL COMMENT '이력서_자기소개서',
    `CV_ALIAS` NVARCHAR2(30) NULL COMMENT '이력서_별칭',
    `CV_IMG_PATH` NVARCHAR2(200) NULL COMMENT '이력서_이미지경로',
    `CV_MAIN_FL` CHAR(1) NULL COMMENT '이력서_대표_플래그',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PK)',
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`)
);

CREATE TABLE `BOARD` (
    `BOARD_NO` NUMBER PRIMARY KEY,
    `BOARD_TITLE` NVARCHAR2(50) NOT NULL COMMENT '게시글_제목',
    `BOARD_CONTENT` VARCHAR2(4000) NOT NULL COMMENT '게시글_내용',
    `BOARD_WRITE_DATE` DATE NOT NULL DEFAULT SYSDATE COMMENT '게시글_작성일',
    `BOARD_EDIT_DATE` DATE NULL COMMENT '게시글_수정일',
    `BOARD_READ_COUNT` NUMBER NOT NULL DEFAULT 0 COMMENT '게시글_조회수',
    `BOARD_STATUS_CODE` NUMBER NOT NULL DEFAULT 0 COMMENT '게시글_상태구분_코드',
    `BOARD_STATUS_DATE` DATE NULL COMMENT '게시글_정지/삭제_날짜',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (FK)',
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`)
);

CREATE TABLE `RECRUIT` (
    `RECRUIT_NO` NUMBER PRIMARY KEY,
    `RECRUIT_TITLE` NVARCHAR2(50) NOT NULL COMMENT '공고_제목',
    `RECRUIT_START_DATE` DATE NOT NULL DEFAULT SYSDATE COMMENT '공고_채용시작일',
    `RECRUIT_END_DATE` DATE NOT NULL COMMENT '공고_채용종료일',
    `RECRUIT_TYPE` NVARCHAR2(15) NOT NULL COMMENT '공고_고용형태',
    `RECRUIT_DOCX` NVARCHAR2(100) NULL COMMENT '공고_제출서류',
    `RECRUIT_APPLY` NVARCHAR2(500) NULL COMMENT '공고_접수방법',
    `RECRUIT_RESULT_DATE` DATE NOT NULL COMMENT '공고_합격자발표일',
    `RECRUIT_CORP_URL` NVARCHAR2(50) NULL COMMENT '공고_채용사이트URL',
    `RECRUIT_HIRE_DETAIL` NVARCHAR2(1000) NULL COMMENT '공고_채용단계상세설명',
    `RECRUIT_JOB_NAME` NVARCHAR2(50) NOT NULL COMMENT '공고_직무명',
    `RECRUIT_JOB_DETAIL` NVARCHAR2(500) NOT NULL COMMENT '공고_직무설명',
    `RECRUIT_JOB_AREA` NVARCHAR2(100) NOT NULL COMMENT '공고_근무지',
    `RECRUIT_CAREER` NVARCHAR2(10) NOT NULL COMMENT '공고_지원자격_경력',
    `RECRUIT_EDU` NVARCHAR2(50) NOT NULL COMMENT '공고_지원자격_학력',
    `RECRUIT_HEADCOUNT` NUMBER NOT NULL COMMENT '공고_모집인원',
    `RECRUIT_SALARY` NVARCHAR2(100) NOT NULL COMMENT '공고_연봉',
    `RECRUIT_ETC` NVARCHAR2(1000) NULL COMMENT '공고_기타사항',
    `RECRUIT_READCOUNT` NUMBER NOT NULL DEFAULT 0 COMMENT '공고_조회수',
    `RECRUIT_STATUS` NUMBER NOT NULL DEFAULT 0 COMMENT '공고_상태구분_코드',
    `RECRUIT_STATUS_DATE` DATE NULL COMMENT '공고__정지/삭제_날짜',
    `RECRUIT_WRITE_DATE` DATE NOT NULL COMMENT '공고_작성일',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PFK)',
    FOREIGN KEY (`MEM_NO`) REFERENCES `CORP_MEM` (`MEM_NO`)
);

CREATE TABLE `BILLING_KEY` (
    `BILLING_KEY` NVARCHAR2(200) PRIMARY KEY,
    `BILLING_METHOD` NVARCHAR2(20) NOT NULL COMMENT '결제_수단',
    `CARD_COMPANY` NVARCHAR2(50) NOT NULL COMMENT '카드사',
    `CARD_NUMBER` NVARCHAR2(25) NOT NULL COMMENT '카드번호',
    `CARD_TYPE` NVARCHAR2(10) NOT NULL COMMENT '카드_유형(신용/체크)',
    `OWNER_TYPE` NVARCHAR2(10) NOT NULL COMMENT '카드_소지자_유형',
    `ISSUER_CODE` NVARCHAR2(10) NOT NULL COMMENT '카드_발급사_코드',
    `ACQUIRER_CODE` NVARCHAR2(10) NOT NULL COMMENT '카드_매입사_코드',
    `AUTHENTICATED_AT` DATE NOT NULL COMMENT '빌링_키_인증_시각',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (FK)',
    `MID` VARCHAR(255) NOT NULL COMMENT '가맹점_식별코드',
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`)
);

-- 종속 테이블들
CREATE TABLE `FAV_RECRUIT` (
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PFK)',
    `RECRUIT_NO` NUMBER NOT NULL COMMENT '공고_시퀀스_번호(PFK)',
    PRIMARY KEY (`MEM_NO`, `RECRUIT_NO`),
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`),
    FOREIGN KEY (`RECRUIT_NO`) REFERENCES `RECRUIT` (`RECRUIT_NO`)
);

CREATE TABLE `CV_EDUCATION` (
    `CV_NO` NUMBER PRIMARY KEY,
    `EDU_NAME` NVARCHAR2(20) NOT NULL COMMENT '학력_학교명',
    `EDU_START_DATE` DATE NOT NULL COMMENT '학력_입학년월일',
    `EDU_END_DATE` DATE NOT NULL COMMENT '학력_졸업년월일',
    `EDU_MAJOR` NVARCHAR2(20) NOT NULL COMMENT '학력_전공',
    `EDU_CODE_NO` NUMBER NOT NULL COMMENT '학력학위_코드',
    `EDU_STATUS_CODE_NO` NUMBER NOT NULL COMMENT '학력상태_코드',
    FOREIGN KEY (`CV_NO`) REFERENCES `CV` (`CV_NO`),
    FOREIGN KEY (`EDU_CODE_NO`) REFERENCES `CV_EDU_CODE` (`EDU_CODE_NO`),
    FOREIGN KEY (`EDU_STATUS_CODE_NO`) REFERENCES `CV_EDU_STATUS` (`EDU_STATUS_CODE_NO`)
);

CREATE TABLE `BOARD_IMG` (
    `BOARD_IMG_NO` NUMBER PRIMARY KEY,
    `BOARD_IMG_URL` NVARCHAR2(500) NOT NULL COMMENT '게시글_이미지_URL',
    `BOARD_IMG_NAME` NVARCHAR2(255) NOT NULL COMMENT '게시글_이미지_이름',
    `BOARD_IMG_UPLOAD_DATE` DATE NOT NULL DEFAULT SYSDATE COMMENT '게시글_이미지_업로드_날짜',
    `BOARD_NO` NUMBER NOT NULL COMMENT '게시글_시퀀스_번호(FK)',
    FOREIGN KEY (`BOARD_NO`) REFERENCES `BOARD` (`BOARD_NO`)
);

CREATE TABLE `FAV_CORP` (
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PK)',
    `CORP_NO` NUMBER NOT NULL COMMENT '기업_시퀀스_번호(PK)',
    PRIMARY KEY (`MEM_NO`, `CORP_NO`),
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`),
    FOREIGN KEY (`CORP_NO`) REFERENCES `CORP_INFO` (`CORP_NO`)
);

CREATE TABLE `SUBSCRIPTION` (
    `SUB_NO` NUMBER NOT NULL COMMENT '구독_번호',
    `MEM_GRADE` NUMBER NOT NULL DEFAULT 0 COMMENT '회원_멤버쉽구분_번호(FK)',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (FK)',
    `SUB_START_AT` DATE NOT NULL DEFAULT SYSDATE COMMENT '구독_시작일',
    `SUB_END_AT` DATE NULL COMMENT '구독_만기일',
    `SUB_UPDATE_AT` DATE NULL COMMENT '구독_변경일',
    `SUB_PAY_AT` DATE NULL COMMENT '구독_결제일',
    `SUB_STATUS` NUMBER NOT NULL DEFAULT 0 COMMENT '구독_상태구분_코드',
    FOREIGN KEY (`MEM_GRADE`) REFERENCES `MEMBER_GRADE` (`MEM_GRADE_NO`),
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`)
);

CREATE TABLE `RECRUIT_CV` (
    `RECRUIT_CV_NO` NUMBER PRIMARY KEY,
    `RECRUIT_CV_EDU` NUMBER NULL COMMENT '지원자_학력',
    `RECRUIT_CV_CAREER` NUMBER NULL COMMENT '지원자_경력',
    `RECRUIT_CV_PDF_TITLE` NVARCHAR2(200) NULL COMMENT '지원자_이력서_PDF_제목',
    `RECRUIT_CV_PDF_PATH` NVARCHAR2(50) NULL COMMENT '지원자_이력서_PDF_경로',
    `RECRUIT_CV_DATE` DATE NULL DEFAULT SYSDATE COMMENT '지원자_지원날짜',
    `RECRUIT_CV_CHECK_FL` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '지원자_이력서_다운로드_여부',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PK)',
    `RECRUIT_NO` NUMBER NOT NULL COMMENT '공고_시퀀스_번호(PK)',
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`),
    FOREIGN KEY (`RECRUIT_NO`) REFERENCES `RECRUIT` (`RECRUIT_NO`)
);

CREATE TABLE `REPORT` (
    `REPORT_NO` NUMBER PRIMARY KEY,
    `REPORT_TARGET_NO` NUMBER NOT NULL COMMENT '신고_대상_시퀀스_번호',
    `REPORT_TARGET_TYPE` NVARCHAR2(10) NOT NULL COMMENT '신고_대상_종류',
    `REPORT_CONTENT` NVARCHAR2(100) NULL COMMENT '신고_내용',
    `REPORT_STATUS` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '신고_처리상태',
    `REPORT_DATE` DATE NOT NULL DEFAULT SYSDATE COMMENT '신고_날짜',
    `REPORT_CATEGORY_CODE` NUMBER NOT NULL COMMENT '신고_카테고리_코드(FK)',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PK)',
    FOREIGN KEY (`REPORT_CATEGORY_CODE`) REFERENCES `REPORT_CATEGORY` (`REPORT_CATEGORY_CODE`),
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`)
);

CREATE TABLE `SUPPORT_NOTICE` (
    `SUPPORT_NOTICE_CODE` NUMBER PRIMARY KEY,
    `SUPPORT_NOTICE_TITLE` NVARCHAR(50) NOT NULL COMMENT '문의_공지_제목',
    `SUPPORT_NOTICE_CONTENT` VARCHAR(4000) NOT NULL COMMENT '문의_공지_내용',
    `SUPPORT_CATEGORY_CODE` NUMBER NOT NULL COMMENT '문의_카테고리_코드(PK)',
    `ADMIN_NO` NUMBER NOT NULL COMMENT '관리자_시퀀스_번호(PK)',
    FOREIGN KEY (`SUPPORT_CATEGORY_CODE`) REFERENCES `SUPPORT_CATEGORY` (`SUPPORT_CATEGORY_CODE`),
    FOREIGN KEY (`ADMIN_NO`) REFERENCES `ADMIN` (`ADMIN_NO`)
);

CREATE TABLE `SUPPORT` (
    `SUPPORT_NO` NUMBER PRIMARY KEY,
    `SUPPORT_CONTENT` VARCHAR2(4000) NOT NULL COMMENT '문의_내용',
    `SUPPORT_ANSWER` VARCHAR2(4000) NULL COMMENT '문의_답변',
    `SUPPORT_STATUS` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '문의_처리상태',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (FK)',
    `ADMIN_NO` NUMBER NOT NULL COMMENT '관리자_시퀀스_번호(FK)',
    `SUPPORT_CATEGORY_CODE` NUMBER NOT NULL COMMENT '문의_카테고리_코드(PK)',
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`),
    FOREIGN KEY (`ADMIN_NO`) REFERENCES `ADMIN` (`ADMIN_NO`),
    FOREIGN KEY (`SUPPORT_CATEGORY_CODE`) REFERENCES `SUPPORT_CATEGORY` (`SUPPORT_CATEGORY_CODE`)
);

CREATE TABLE `BAN` (
    `BAN_NO` NUMBER PRIMARY KEY,
    `BAN_CONTENT` NVARCHAR2(100) NOT NULL COMMENT '정지사유_내용',
    `BAN_TARGET_NO` NUMBER NOT NULL COMMENT '정지_대상_시퀀스_번호',
    `BAN_TARGET_TYPE` NVARCHAR2(10) NOT NULL COMMENT '정지_대상_종류',
    `ADMIN_NO` NUMBER NOT NULL COMMENT '관리자_시퀀스_번호(FK)',
    FOREIGN KEY (`ADMIN_NO`) REFERENCES `ADMIN` (`ADMIN_NO`)
);

CREATE TABLE `CV_PORTFOLIO` (
    `PORT_ID` NVARCHAR2(30) PRIMARY KEY,
    `PORT_NAME` NVARCHAR2(20) NOT NULL COMMENT '포폴_이름',
    `PORT_START_DATE` DATE NOT NULL COMMENT '포폴_시작일',
    `PORT_END_DATE` DATE NOT NULL COMMENT '포폴_종료일',
    `PORT_CONTENT` NVARCHAR2(1000) NULL COMMENT '포폴_내용',
    `CV_NO` NUMBER NOT NULL COMMENT '이력서_시퀀스_번호(PK)',
    FOREIGN KEY (`CV_NO`) REFERENCES `CV` (`CV_NO`)
);

CREATE TABLE `CV_LANGUAGE` (
    `LANG_ID` NVARCHAR2(30) PRIMARY KEY,
    `LANG_NAME` NVARCHAR2(20) NOT NULL COMMENT '어학_이름',
    `LANG_DATE` DATE NOT NULL COMMENT '어학_취득일',
    `LANG_TYPE` NVARCHAR2(20) NOT NULL COMMENT '어학_언어',
    `LANG_SCORE` NUMBER NULL COMMENT '어학_점수',
    `CV_NO` NUMBER NOT NULL COMMENT '이력서_시퀀스_번호(PK)',
    FOREIGN KEY (`CV_NO`) REFERENCES `CV` (`CV_NO`)
);

CREATE TABLE `CV_EXPERIENCE` (
    `EXP_ID` NVARCHAR2(30) PRIMARY KEY,
    `EXP_NAME` NVARCHAR2(20) NOT NULL COMMENT '경력_이름',
    `EXP_START_DATE` DATE NOT NULL COMMENT '경력_시작일',
    `EXP_END_DATE` DATE NOT NULL COMMENT '경력_종료일',
    `EXP_DEPT` NVARCHAR2(20) NOT NULL COMMENT '경력_부서',
    `EXP_CONTENT` NVARCHAR2(1000) NULL COMMENT '경력_내용',
    `CV_NO` NUMBER NOT NULL COMMENT '이력서_시퀀스_번호(PK)',
    FOREIGN KEY (`CV_NO`) REFERENCES `CV` (`CV_NO`)
);

CREATE TABLE `CV_TRAINING` (
    `TRAIN_ID` NVARCHAR2(30) PRIMARY KEY,
    `TRAIN_NAME` NVARCHAR2(20) NOT NULL COMMENT '교육_이름',
    `TRAIN_START_DATE` DATE NOT NULL COMMENT '교육_시작일',
    `TRAIN_END_DATE` DATE NOT NULL COMMENT '교육_종료일',
    `TRAIN_ORGANIZATION` NVARCHAR2(20) NOT NULL COMMENT '교육_기관',
    `TRAIN_CONTENT` NVARCHAR2(1000) NULL COMMENT '교육_내용',
    `CV_NO` NUMBER NOT NULL COMMENT '이력서_시퀀스_번호(PK)',
    FOREIGN KEY (`CV_NO`) REFERENCES `CV` (`CV_NO`)
);

CREATE TABLE `FAV_BOARD` (
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PFK)',
    `BOARD_NO` NUMBER NOT NULL COMMENT '게시글_시퀀스_번호(PFK)',
    PRIMARY KEY (`MEM_NO`, `BOARD_NO`),
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`),
    FOREIGN KEY (`BOARD_NO`) REFERENCES `BOARD` (`BOARD_NO`)
);

CREATE TABLE `PAYMENT` (
    `ORDER_ID` NUMBER PRIMARY KEY,
    `ORDER_NAME` NVARCHAR2(200) NOT NULL COMMENT '주문_명',
    `PAYMENT_KEY` NVARCHAR2(200) NOT NULL COMMENT '결제_키',
    `BILLING_KEY` NVARCHAR2(200) NOT NULL COMMENT '빌링_키(FK)',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (FK)',
    `TOTAL_AMOUNT` NUMBER NOT NULL COMMENT '결제_금액',
    `CURRENCY` NVARCHAR2(5) NOT NULL COMMENT '통화',
    `COUNTRY` NVARCHAR2(2) NOT NULL COMMENT '국가',
    `PAY_TYPE` NVARCHAR2(20) NOT NULL COMMENT '결제_유형',
    `STATUS` NVARCHAR2(20) NOT NULL COMMENT '결제_상태',
    `REQUESTED_AT` DATE NOT NULL COMMENT '결제_요청_시각',
    `APPROVED_AT` DATE NOT NULL COMMENT '결제_승인_시각',
    `UPDATED_AT` DATE NULL COMMENT '주문_수정_시각',
    `CANCELS` NVARCHAR2(5) NULL COMMENT '취소_정보',
    `FAILURE` NVARCHAR2(5) NULL COMMENT '실패_정보',
    FOREIGN KEY (`BILLING_KEY`) REFERENCES `BILLING_KEY` (`BILLING_KEY`),
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`)
);

CREATE TABLE `REFUND` (
    `REFUND_ID` NUMBER NOT NULL,
    `REFUND_REQUEST_AT` DATE NOT NULL DEFAULT SYSDATE,
    `REFUND_SUCCESS_AT` DATE NULL,
    `REFUND_STATUS` NVARCHAR2(20) NULL,
    `REFUND_AMOUNT` NUMBER NOT NULL COMMENT '환불액',
    `ORDER_ID` NUMBER NOT NULL COMMENT '주문_ID(FK)',
    `MEM_NO` NUMBER NOT NULL COMMENT '회원_시퀀스_번호 (PK)',
    FOREIGN KEY (`ORDER_ID`) REFERENCES `PAYMENT` (`ORDER_ID`),
    FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`)
);

CREATE TABLE `CV_AWARD` (
    `AWARD_ID` NVARCHAR2(30) PRIMARY KEY,
    `AWARD_NAME` NVARCHAR2(20) NOT NULL COMMENT '수상_이름',
    `AWARD_DATE` DATE NOT NULL COMMENT '수상_취득일',
    `AWARD_ORG` NVARCHAR2(20) NOT NULL COMMENT '수상_기관',
    `CV_NO` NUMBER NOT NULL COMMENT '이력서_시퀀스_번호(PK)',
    FOREIGN KEY (`CV_NO`) REFERENCES `CV` (`CV_NO`)
);

CREATE TABLE `COMMENT` (
    `COMMENT_NO` NUMBER PRIMARY KEY,
    `COMMENT_CONTENT` NVARCHAR2(1000) NOT NULL COMMENT '댓글_내용',
    `COMMENT_WRITE_DATE` DATE NOT NULL COMMENT '댓글_작성일',
    `COMMENT_EDIT_DATE` DATE NULL COMMENT '댓글_수정일',
    `COMMENT_STATUS` NUMBER NOT NULL DEFAULT 0 COMMENT '댓글_상태구분_코드',
    `COMMENT_STATUS_DATE` DATE NULL COMMENT '댓글_정지/삭제_날짜',
    `BOARD_NO` NUMBER NOT NULL COMMENT '게시글_시퀀스_번호(FK)',
    `PARENT_COMMENT_NO` NUMBER NULL COMMENT '부모_댓글_시퀀스_번호(FK)',
    FOREIGN KEY (`BOARD_NO`) REFERENCES `BOARD` (`BOARD_NO`),
    FOREIGN KEY (`PARENT_COMMENT_NO`) REFERENCES `COMMENT` (`COMMENT_NO`)
);

CREATE TABLE `AUTH` (
    `AUTH_NO` NUMBER PRIMARY KEY,
    `AUTH_PHONE` NVARCHAR2(11) NOT NULL COMMENT '인증_전화번호',
    `AUTH_KEY` NVARCHAR2(10) NOT NULL COMMENT '인증_인증번호',
    `AUTH_TIME` DATE NOT NULL DEFAULT SYSDATE COMMENT '인증_생성